displayName: <h2> Account Management </h2>
description: This API handles Accounts and User related operations
post:
  description: |
    **Create an Account**

    Important: After creating account, user Authorization token must be refreshed to access the new account data.

    <meta name="access-roles" path="POST:/api/accounts">
  is: [ authorization-header, response-errors-acounts, response-errors-generic ]
  body:
    application/json:
      type: !include account_ACCOUNT.json
      example:
        {
          "name": "AccountName"
        }
  responses:
    201:
      body:
        application/json:
          example: |
            { 
              "name":"AccountName",
              "healthTimePeriod":86400,
              "created":1406919627586,
              "updated":1406919627586,
              "exec_interval":300,
              "base_line_exec_interval":86400,
              "cd_model_frequency":604800,
              "cd_execution_frequency":600,
              "data_retention":0,
              "id":"321ef007-8449-477f-9ea0-d702d77e64b9"
            }
/{accountId}:
  uriParameters:
    accountId:
      description: |
        The ID of an Account. In order to obtain the Account Id, we need first obtain an Authorization Token and then get the Authorization Token Info
      example: 321ef007-8449-477f-9ea0-d702d77e64b9
  get:
    is: [ authorization-header, response-errors-acounts, response-errors-generic ]
    description: |
      **Get Account information**

      <meta name="access-roles" path="GET:/api/accounts/{accountId}">
    responses:
      200:
        body:
          application/json:
            example: |
              {  
                "name": "AccountName",
                "healthTimePeriod": 86400,
                "created": 1404415261310,
                "updated": 1404415261310,
                "exec_interval": 120,
                "base_line_exec_interval": 86400,
                "cd_model_frequency": 604800,
                "cd_execution_frequency": 600,
                "data_retention": 0,
                "attributes":{
                  "phone":"123456789",
                  "another_attribute":"another_value"
                },
                "id": "321ef007-8449-477f-9ea0-d702d77e64b9"
              }
  put:
    description: |
      **Update an Account**

      <meta name="access-roles" path="PUT:/api/accounts/{accountId}">
    is: [ authorization-header, responses-successful, response-errors-acounts, response-errors-generic ]
    body:
      application/json:
        type: !include account_UPDATE.json
        example: |
          {
            "name": "NEWAccountName",
            "healthTimePeriod": 86400,        
            "exec_interval": 120,
            "base_line_exec_interval": 86400,
            "cd_model_frequency": 604800,
            "cd_execution_frequency": 600,
            "data_retention": 0,
            "attributes":{
              "phone":"123456789",
              "another_attribute":"another_value",
              "new":"next_string_value"
            },
            "id": "321ef007-8449-477f-9ea0-d702d77e64b9"
          }
  delete:
    description: |
      **Delete an Account.**

      Deletes an Account and all its data.

      <meta name="access-roles" path="DELETE:/api/accounts/{accountId}">
    is: [ authorization-header, response-errors-acounts, response-errors-generic ]
    responses:
      204:
        description: NO CONTENT
  /activationcode:
    get:
      description: |
        **Get Account Activation Code**

        The Account Activation Code is the transient activation code that can be used to activate devices for the account. It expires after one hour.

        <meta name="access-roles" path="GET:/api/accounts/{accountId}/activationcode">
      is: [ authorization-header, response-errors-acounts, response-errors-generic ]
      responses:
        200:
          description: OK
          body:
            application/json:
              example: |
                {
                  "activationCode": "CgSVoHee",
                  "timeLeft": 1404418861
                }
    /refresh:
      put:
        description: |
          **Renew Account Activation Code**

          Forces the renewal of the Account Activation Code.

          <meta name="access-roles" path="PUT:/api/accounts/{accountId}/activationcode/refresh">
        is: [ authorization-header, response-errors-acounts, response-errors-generic ]
        responses:
          200:
            body:
              application/json:
                example:
                  {
                    "activationCode": "bBnvBWrT",
                    "timeLeft": 1404419896
                  }
  /users/{userId}:
    uriParameters:
      userId:
        description: The ID of User you would like to add account for
        example: 53e95985c8406a147700b94d
    put:
      description: |
        **Change another user privileges to your account (you need to be an admin)**

        You can upgrade a standard user of your account (who currently has "user" privileges - default for invited users) to an admin. To do so, you have to be an admin of account for which you want to upgrade another user's access. {role} is supposed to be "user" or "admin".

        Remember that user can be promoted from user to admin, but admin privileges cannot be revoked.

        <meta name="access-roles" path="PUT:/api/accounts/{accountId}/users/{userId}">
      is: [ authorization-header, responses-successful, response-errors-acounts, response-errors-generic]
      body:
        application/json:
          type: !include user_PUT.json
          example: |
            {
              "id": "{userId}",
              "accounts": {
                "{accountId}": "{role}"
              }
            }    
