#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

displayName: <h2> Alert Management </h2>
description: |
  The Alert API is a REST Interface for handling alerts.
uriParameters:
  accountId:
    description: |
      The ID of an Account. In order to obtain the Account Id, we need first obtain an Authorization Token and then get the Authorization Token Info
    example: 321ef007-8449-477f-9ea0-d702d77e64b9
get:
  description: |
    **Get List of Alerts**
      
    Get a list of all alerts for the specified account.

    <meta name="access-roles" path="GET:/api/accounts/{accountId}/alerts">
  is: [ authorization-header, response-errors-alerts, response-errors-generic ]
  responses:
    200:
      description: OK
      body:
        application/json:
          example: |
            [
            {
              "accountId": "0d66c8b6-9f4d-4551-a9c8-d356c2dd033d",
              "alertId": "75",
              "deviceId": "00-00-00-00-a8-9c",
              "ruleId": 6832,
              "ruleName": "rule 2 - basic condition new",
              "priority": "Low", 
              "triggered": 1402580459000,
              "created": 1411130946286,
              "naturalLangAlert": "temperature > 17.2",
              "conditions": [
              {
                "sequence": 1,
                "condition": "temperature > 17.2"
              }
              ],
              "status": "New",
              "updated": 1411130946286,
              "_id": "541c2642b3700bcbe9c76fc5"
            }
            ]
/{alertId}:
  uriParameters:
    alertId:
      description: **The ID of an Alert**
      example: 75
  get:
    is: [ authorization-header, response-errors-alerts, response-errors-generic ]
    description: |
      **Get Alert information**

      Get specific alert details connected with the account.

      <meta name="access-roles" path="GET:/api/accounts/{accountId}/alerts/{alertId}">
    responses:
      200:
        description: OK
        body:
          application/json:
            example: |
              {
                "accountId": "0d66c8b6-9f4d-4551-a9c8-d356c2dd033d",
                "alertId": "75",
                "deviceId": "00-00-00-00-a8-9c",
                "ruleId": 6832,
                "ruleName": "rule 2 - basic condition new",
                "priority": "Low",
                "triggered": 1402580459000,
                "created": 1411130946286,
                "naturalLangAlert": "temperature > 17.2",
                "conditions": [
                {
                  "sequence": 1,
                  "condition": "temperature > 17.2",
                  "components": [
                  {
                    "componentId": "e5f09130-c70e-4082-9801-49833c853493",
                    "dataType": "Number",
                    "componentName": "GA9c-3-Temp.Sensor",
                    "valuePoints": [
                    {
                      "timestamp": 1402580459000,
                      "value": "21"
                    }
                    ]
                  }
                  ]
                }
                ],
                "status": "New",
                "updated": 1411130946286,
                "_id": "541c2642b3700bcbe9c76fc5"
              }
  /reset:
    put:
      description: |
        **Reset Alert**

        Change alert status to - "Closed". Alert won't be active any more.

        <meta name="access-roles" path="PUT:/api/accounts/{accountId}/alerts/{alertId}/reset">
      is: [ authorization-header, responses-successful, response-errors-alerts, response-errors-generic ]
  /status/{statusName}:
    uriParameters:
      statusName:
        description: The Name of a new alert status. Should be one of ['New', 'Open', 'Closed']
        example: "Closed"
    put:
      description: |
        **Update Alert status**

        Change status of the Alert. Status should have one of the following values: ['New', 'Open', 'Closed']

        <meta name="access-roles" path="PUT:/api/accounts/{accountId}/alerts/{alertId}/status/{statusName}">
      is: [ authorization-header, responses-successful, response-errors-alerts, response-errors-generic ]
  /comments:
    post:
      is: [ authorization-header, responses-successful, response-errors-alerts, response-errors-generic ]
      description: |
        **Add comments to the Alert**
        
        Add list of comments to the alert.

        <meta name="access-roles" path="PUT:/api/accounts/{accountId}/alerts/{alertId}/comments">
      body:
        application/json:
          type: !include alert_COMMENTS.json
          example:
            [
            {
              "user": "test@example.com",
              "timestamp": 123233231221,
              "text": "comment"
            }
            ]