#%RAML 1.0
#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
title: Open IOT Connector (OIC) RESTful
baseUri: https://streammyiot.com
mediaType: [ application/json ]
version: v1
        
traits:
  authorization-header:
    headers:
      Authorization:
        description: "This header is used to transmit a valid JWT as follows: Bearer JWT"
        example: "Authorization: Bearer eyJ0eXAi.."
  responses-successful:
    responses:
      200:
        description: OK
  responses-created:
    responses:
      201:
        description: CREATED
  response-errors-users:
    !include build/errors_User.raml
  response-errors-acounts:
    !include build/errors_Account.raml
  response-errors-rules:
    !include build/errors_Rule.raml
  response-errors-alerts:
    !include build/errors_Alert.raml
  response-errors-devices:
    !include build/errors_Device.raml
  response-errors-invitation:
    !include build/errors_Invite.raml
  response-errors-complex-command:
    !include build/errors_ComplexCommand.raml
  response-errors-actuation:
    !include build/errors_Actuation.raml
  response-errors-component:
    !include build/errors_Component.raml
  response-errors-data:
    !include build/errors_Data.raml
  response-errors-generic:
    !include build/errors_Generic.raml

#Auth API
/v1/api/auth:
  !include build/auth.raml
  

#Users API
/v1/api/users:
  !include build/users.raml


#Accounts API
/v1/api/accounts:
  !include build/accounts.raml


#Rules API
/v1/api/accounts/{accountId}/rules:
  !include build/rules.raml


#Alert API
/v1/api/accounts/{accountId}/alerts:
  !include build/alerts.raml


#Devices API
/v1/api/accounts/{accountId}/devices:
  !include build/devices.raml


#Advanced Data API
/v1/api:
  !include build/data.raml


#Component Types Catalog
/v1/api/accounts/{accountId}/cmpcatalog:
  !include build/component-types.raml


#Control Device API
/v1/api/accounts/{accountId}/control:
  !include build/control-device.raml


#Invitation Management
/v1/api/accounts/{accountId}/invites:
  !include build/invitation-management.raml