#
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

displayName: <h2> Component Types Catalog </h2>
description: |
  The Component Types Catalog API is a REST Service for maintaining a list of capabilities (with its associated data) that components connected to enableiot platform expose.

  There are two main types of components:
    * Sensor
    * Actuator 

    The catalog comes with *default* (built-in) component types which are available to all accounts (see the list [here](Component Types List)).
    These components will have the `default` field set to true.
    Each account can additionaly define *custom* component type which will be available only within that account. 

    A *Component-Type ID*, which is account-level unique is a concatenation of its dimension and its version, seperated by a single period: e.g. "temperature.v1.0" or "humidity.v2.0".

    See section on Device-Management for an example of registering list of components associated to a Device.
uriParameters:
  accountId:
    description: |
      The ID of an Account. In order to obtain the Account Id, we need first obtain an Authorization Token and then get the Authorization Token Info
    example: 321ef007-8449-477f-9ea0-d702d77e64b9
get:
  description: |
    **List all Component Types for an Account**

    Get a list of all Component Types, with minimal data for each component if `full` paramter is omitted or `false`. If `full=true` the detailed data is retrieved.

    <meta name="access-roles" path="GET:/api/accounts/{accountId}/cmpcatalog">
  is: [ authorization-header, response-errors-component, response-errors-generic ]
  queryParameters:
    full:
      description: if true the complete description is sent, otherwise only a condensed one.
      required: false
      example: true
      type: boolean
  responses:
    200:
      description: OK
      body:
        examples:
          example-minimal: |
            [
            {
              "id":"temperature.v2.0",
              "dimension": "temperature",
              "version": "2.0",
              "type": "sensor",
              "href": "<protocol>://<server:port>/cmpcatalog/temperature.v2.0"
            },
            {
              "id":"humidity.v1.0",
              "dimension": "humidity",
              "version": "1.0",
              "type": "sensor",
              "href": "<protocol>://<server:port>/cmpcatalog/humidity.v1.0"
            },
            {
              "id":"powerswitch.v1.0",
              "dimension": "powerswitch",
              "version": "1.0",
              "type": "actuator",
              "href": "<protocol>://<server:port>/cmpcatalog/powerswitch.v1.0"
            },		
            ]
          example-detailed: |
            [
            {                        
              "id":"temperature.v1.0",
              "dimension": "temperature",
              "version": "1.0",
              "default": true,
              "type": "sensor",
              "dataType":"Number",
              "format": "float",
              "min": 0,
              "max": 100,
              "measureunit": "Percent (%)",
              "display": "Dimmer",
              "href": "<protocol>://<server:port>/cmpcatalog/temperature.v1.0"
            },
            {                        
              "id":"powerswitch.v2.0",
              "dimension": "powerswitch",
              "version": "2.0",
              "default": true,
              "type": "sensor",
              "dataType":"Number",
              "format": "float",
              "min": 0,
              "max": 1,
              "measureunit": "Boolean",
              "display": "Dimmer",
              "href": "<protocol>://<server:port>/cmpcatalog/powerswitch.v2.0"
            }
            ]
post:
  description: |
    **Create a new custom Component Type**

    When creating a brand new component, dimension and version attributes are used for determining if the component exists. If not, a new component is created which auto-generated id results the concatenation of dimension and version values.

    <meta name="access-roles" path="POST:/api/accounts/{accountId}/cmpcatalog">
  is: [ authorization-header, response-errors-component, response-errors-generic ]
  body:
    type: !include component_POST.json
    example:
      {	
        "dimension": "temperature",
        "version": "2.0",
        "type": "sensor",
        "dataType":"Number",
        "format": "float",
        "min": -150,
        "max": 150,
        "measureunit": "Degress Celsius",
        "display": "timeSeries"
      }
  responses:
    201:
      description: CREATED
      {
        "id":"temperature.v2.0",
        "dimension": "temperature",
        "version": "2.0",
        "type": "sensor",
        "dataType":"Number",
        "format": "float",
        "min": -150,
        "max": 150,
        "measureunit": "Degress Celsius",
        "display": "timeSeries",
        "href": "<protocol>://<server:port>/cmpcatalog/temperature.v2.0"
        }
/{componentId}:
  uriParameters:
    componentId:
      description: The ID of a specific component on Domain's catalog
      example: Powerswitch.v2.0
  get:
    description: |
      **Get Component Type Details**

      Get a complete description of a component type specified by Id

      <meta name="access-roles" path="GET:/api/accounts/{accountId}/cmpcatalog/{componentId}">
    is: [ authorization-header, response-errors-component, response-errors-generic ]
    responses:
      200:
        description: OK
        body:
          example: |
            {
              "id":"powerswitch.v2.0",
              "dimension": "powerswitch",
              "version": "2.0",
              "default": true,
              "type": "actuator",
              "dataType":"Number",
              "format": "float",
              "min": 0,
              "max": 100,
              "measureunit": "Percent (%)",
              "display": "Dimmer",
              "href": "<protocol>://<server:port>/cmpcatalog/powerswitch.v2.0"
            }
  put:
    description: |
      **Update a Component Type**

      Updates a component type definition by creating a brand new component which definition is composed by the origin component data plus the requested changes having in mind that minor version info (version attribute) is incremented by 1.

      <meta name="access-roles" path="PUT:/api/accounts/{accountId}/cmpcatalog/{componentId}">
    is: [ authorization-header, response-errors-component, response-errors-generic ]
    body:
      type: !include component_PUT.json
      example: |
        {			
          "format": "integer",
          "min": 0,
          "max": 100		
        }
    responses:
      201:
        description: CREATED
        body:
          example:
            {
              "id":"temperature.v2.1",
              "dimension": "temperature",
              "version": "2.1",
              "type": "sensor",
              "dataType":"Number",
              "format": "integer",
              "min": 0,
              "max": 100,
              "measureunit": "Degress Celsius",
              "display": "timeSeries",
              "href": "<protocol>://<server:port>/cmpcatalog/temperature.v2.1"
            }