name: End2End Test
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - '**-debugtest'
jobs:
  build:
    env:
      SELF_HOSTED_RUNNER: true
    runs-on: private
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Open-IoT-Service-Platform/platform-launcher.git
        ref: 'develop'
        path: platform-launcher
    - name: Setup main repo + subrepos
      shell: bash
      run: |
        export TERM=vt100
        if [ -z "${SELF_HOSTED_RUNNER}" ]; then
          sudo apt install jq
        fi
        cd platform-launcher
        git submodule update --init --recursive
        make update
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        path: platform-launcher/oisp-frontend
    - name: Prepare platform
      shell: bash
      working-directory: platform-launcher
      run: |
        export TERM=vt100
        if [ -z "${SELF_HOSTED_RUNNER}" ]; then
          cd util && \
          bash setup-ubuntu20.04.sh
        else
          make restart-cluster
        fi
    - name: Build platform
      working-directory: platform-launcher
      shell: bash
      run: |
        set +o pipefail
        export TERM=vt100
        yes | DOCKER_TAG=test NODOCKERLOGIN=true DEBUG=true make build
    - name: E2E Test
      id: e2etest
      working-directory: platform-launcher
      shell: bash
      run: |
        set +e
        export TERM=vt100
        export PATH=$PATH:/snap/bin
        make import-images DOCKER_TAG=test DEBUG=true
        docker image prune -a -f
        rm -rf oisp-*
        npm install nodemailer
        export NODOCKERLOGIN=true
        retval=2
        loops=0
        export DOCKER_TAG=test
        export USE_LOCAL_REGISTRY=true
        until [ ${retval} -eq 0 ] || [ ${loops} -gt 3 ]; do
          make undeploy-oisp
          (for i in {1..20}; do sleep 60; echo .; done&) &&  make deploy-oisp-test
          make test
          retval=$?
          loops=$((loops+1))
        done
        echo Test return value: ${retval}
        exit ${retval}
